keybinding:
  universal:
    return: '<c-x>'

gui:
  theme:
    inactiveBorderColor:
    - cyan
    activeBorderColor:
    - magenta
    - bold

customCommands:
  - key: '<c-p>'
    command: 'git push origin HEAD:refs/for/master'
    context: 'commits'
    stream: true
    loadingText: 'Pushing to remote master branch'
    description: 'Custom: Do git push origin HEAD:refs/for/master'
  - key: '<c-p>'
    command: 'git pull --rebase'
    context: 'localBranches'
    stream: true
    loadingText: 'Pulling then rebase'
    description: 'Custom: Do git pull --rebase'
  - key: '<c-f>'
    command: 'git fetch'
    context: 'localBranches'
    stream: true
    loadingText: 'Fetching...'
    description: 'Custom: Do git fetch'
  - key: 'o'
    command: './scripts/open-commit-lazygit.sh {{.SelectedLocalCommit.Hash}}'
    context: 'commits'
    stream: true
    loadingText: 'Openning {{.SelectedLocalCommit.Hash}}'
    description: 'Custom: Do - open commit from browser'
    subprocess: true
- key: '<c-o>'
    command: './scripts/copy-commit-lazygit.sh {{.SelectedLocalCommit.Hash}}'
    context: 'commits'
    stream: true
    loadingText: 'Copy {{.SelectedLocalCommit.Hash}}'
    description: 'Custom: Do - copy commit url to clipboard'
    subprocess: true
git:
  autoFetch: false
